---
engines:
  checkstyle:
    enabled: true
    channel: beta
    config: 'checkstyle.xml'
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: beta
ratings:
  paths:
  - "**.java"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - "mdoclet/resources/"
  - "mdoclet/stylesheet.css"
